name: Update Zipcode Data

on:
  schedule:
    # 毎週月曜日の午前9時（JST）に実行
    - cron: '0 0 * * 1'
  workflow_dispatch: # 手動実行も可能

jobs:
  update-data:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./script
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true   # push で認証情報を利用
          fetch-depth: 0             # 完全な履歴を取得してブランチ追跡
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: script/package-lock.json
          
      - name: Install dependencies
        run: npm ci
          
      - name: Run data update
        id: update
        run: npm run exec
        
      - name: Check if data was updated
        id: check
        run: |
          if git diff --quiet data/; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Commit and push changes
        if: steps.check.outputs.no_changes == 'false'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -B main
          git add ../data/
          git commit -m "Update zipcode data [skip ci]" || echo "No changes to commit"
          git push origin main
          
      - name: Create issue on failure
        if: steps.update.outcome == 'failure'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Zipcode data update failed',
              body: 'The scheduled zipcode data update failed. Please check the workflow logs.',
              labels: ['bug', 'automation']
            })
