name: Update Zipcode Data

on:
  schedule:
    # 毎週月曜日の午前9時（JST）に実行
    - cron: '0 0 * * 1'
  workflow_dispatch: # 手動実行も可能

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          cd script
          npm ci
          
      - name: Run data update
        id: update
        run: |
          cd script
          npm run exec
        continue-on-error: true
        
      - name: Check if data was updated
        id: check
        run: |
          if git diff --quiet data/; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Commit and push changes
        if: steps.check.outputs.no_changes == 'false'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/
          git commit -m "Update zipcode data [skip ci]"
          git push
          
      - name: Create issue on failure
        if: failure() && steps.update.outcome == 'failure'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Zipcode data update failed',
              body: 'The scheduled zipcode data update failed. Please check the workflow logs.',
              labels: ['bug', 'automation']
            })
